Actionification
iron-claw-972/FRC2020 pull request #88
Opened 2020-02-20 00:21 UTC by Maciej4

This adds a new object, Trigger.java, that should allow for the addition of actions to the parallel scheduler on the press of a button. It also includes two tests.

2020-02-21 21:30 UTC, HoldenA1 requested changes
Bulk of the code looks fine, but some things should be addressed

2020-02-21 21:30 UTC, HoldenA1 commented on src/main/java/frc/robot/actions/VisionAlign.java
> +        //TODO: Combine track cancelling into action
There is a lot of commented code here. The main branch should be only working code. If the code is incomplete, it probably shouldn't be merged yet. If this part is being worked on in another branch it should be merged there first.

2020-02-21 21:30 UTC, HoldenA1 commented on src/main/java/frc/robot/util/Trigger.java
> +            String seralized = gson.toJson(this.action);
It isn't obvious what a google library for converting stuff to JSON is doing here. This a place where comments would be nice to have.

2020-02-21 21:30 UTC, HoldenA1 commented on src/test/java/frc/robot/controllers/DriverJoystickTest.java
> +        {
While code style really isn't that big of an issue, the curly braces are very inconsistent. The opening curly braces should all be on the same line as the function declaration. This should not change for if statements, for loops, while loops, or class declarations. It just has to be consistent.

2020-02-23 07:55 UTC, Maciej4 commented
I think that I have fixed all of the issues you have posed.

2020-02-24 00:57 UTC, HoldenA1 submitted a review, later dismissed
Looks good now.

2020-02-24 17:40 UTC, Maciej4 commented
Fixed merge conflicts, which merged into branch and dismissed review. Sorry about that, could you re-review.

2020-02-24 17:56 UTC, HoldenA1 approved these changes
Rip github

2020-02-24 22:34 UTC, merged